modLoader="javafml" #mandatory
loaderVersion="${forge_range}" #mandatory
license="MIT"
issueTrackerURL="https://github.com/ChiefArug/Thermalthermaloot/issues" #optional
[[mods]] #mandatory
modId="thermaloot" #mandatory
version="${thermaloot_version}" #mandatory
displayName="Thermaloot" #mandatory
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/thermaloot" #optional
logoFile="pack.png" #optional
credits="Thanks to all the people who make the Thermal Series of mods, and all those who have provided feedback/suggestions for Thermaloot" #optional
authors="ChiefArug" #optional
description='''
The latest and greatest loot based augment randomisation mod.
Collect Capacitors from all sorts of loot chests, including end city, ancient city, desert pyramid, buried treasure, mineshafts and more, then use them to power up (or power down) your machines.
From Sad Capacitors to Huge Sentient Capacitors of Wonder, they are all yours!
'''
[[dependencies.thermaloot]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_range}" #mandatory
[[dependencies.thermaloot]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
[[dependencies.thermaloot]]
    modId="thermal_expansion"
    mandatory=true
    versionRange="${thermal_expansion_range}"