@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package chiefarug.mods.thermaloot.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;